[package]
name = "blog_os"
version = "0.2.0"
authors = ["user <user@example.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.2.3"
rlibc = "1.0"
spin = "*"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

