#!/bin/bash
sudo apt install curl -y
curl https://sh.rustup.rs -sSf -o rustup.sh
sh ./rustup.sh -y
rm ./rustup.sh

export PATH="${HOME}/.cargo/bin:${PATH}"
rustup update nightly

sudo apt install make -y
sudo apt install pkg-config -y

if [ -z `which cc` ]; then 
	sudo apt install gcc -y
fi

cargo install xargo
cargo install bootimage

rustup component add rust-src

sudo apt install qemu-system-x86 -y
